# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, choices=[('U', 'Unknown'), ('TNR', 'TNR'), ('Kindergarden', 'Kindergarden'), ('Best Friends', 'Best Friends'), ('LAAS', 'LAAS')], default='U', max_length=1, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('D', 'Deceased'), ('P', 'Predation'), ('A', 'Adopted'), ('W', 'Working Cat'), ('O', 'Other'), ('U', 'Unknown')], max_length=1, null=True)),
                ('outcome_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unknown')], default='U', max_length=1, null=True)),
                ('laas_id', models.CharField(blank=True, max_length=15, null=True)),
                ('pull_date', models.DateField(blank=True, null=True)),
                ('pull_shelter', models.CharField(blank=True, max_length=20, null=True)),
                ('pulled_by', models.CharField(blank=True, max_length=100, null=True)),
                ('microchip_no', models.CharField(blank=True, max_length=100, null=True)),
                ('microchip_tfx_date', models.DateField(blank=True, null=True)),
                ('sneuter', models.DateField(blank=True, null=True)),
                ('sneuter_location', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingCatApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Placement', 'Placement'), ('Pending', 'Pending'), ('NewContact', 'New Contact')], default='NewContact', max_length=10)),
                ('inventory_loaned', models.CharField(blank=True, max_length=100, null=True)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=100, verbose_name='What is your first name?')),
                ('last_name', models.CharField(max_length=100, verbose_name='What is your family (last) name?')),
                ('email', models.CharField(max_length=100, verbose_name='What is your email?')),
                ('business_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='What is your business name?')),
                ('street_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='What is your street address?')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='What is your city?')),
                ('state', models.CharField(blank=True, default='CA', max_length=2, null=True, verbose_name='What state do you live in?')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='What is your zip code?')),
                ('phone_cell', models.CharField(blank=True, max_length=50, null=True, verbose_name='What is your cell phone number?')),
                ('phone_land', models.CharField(blank=True, max_length=50, null=True, verbose_name='What is your home/business telephone number?')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Describe your need of working cats? ')),
                ('kb_notes', models.TextField(blank=True, null=True, verbose_name='KB Notes')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wc.WorkingCatApplication'),
        ),
    ]
