# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingcatapplication',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='What type of business is this? (i.e., winery, stable, private home, etc.'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='source',
            field=models.CharField(blank=True, choices=[('U', 'Unknown'), ('TNR', 'TNR'), ('LAAS', 'LAAS'), ('Kindergarden', 'Kindergarden'), ('Best Friends', 'Best Friends')], default='U', max_length=1, null=True),
        ),
    ]
