# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0002_auto_20180108_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='source',
            field=models.CharField(blank=True, choices=[('LAAS', 'LAAS'), ('U', 'Unknown'), ('TNR', 'TNR'), ('Kindergarden', 'Kindergarden'), ('Best Friends', 'Best Friends')], default='U', max_length=15, null=True),
        ),
    ]
