# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0003_auto_20180108_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='source',
            field=models.CharField(blank=True, choices=[('Kindergarden', 'Kindergarden'), ('Best Friends', 'Best Friends'), ('U', 'Unknown'), ('TNR', 'TNR'), ('LAAS', 'LAAS')], default='U', max_length=15, null=True),
        ),
    ]
