# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0004_auto_20180109_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='source',
            field=models.CharField(blank=True, choices=[('TNR', 'TNR'), ('Kindergarden', 'Kindergarden'), ('U', 'Unknown'), ('Best Friends', 'Best Friends'), ('LAAS', 'LAAS')], default='U', max_length=15, null=True),
        ),
    ]
