# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0004_auto_20180109_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingcatapplication',
            name='planned_placement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='What is the planned placment date?'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='source',
            field=models.CharField(blank=True, choices=[('Kindergarden', 'Kindergarden'), ('TNR', 'TNR'), ('Best Friends', 'Best Friends'), ('U', 'Unknown'), ('LAAS', 'LAAS')], default='U', max_length=15, null=True),
        ),
    ]
