# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0005_auto_20180109_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingcatapplication',
            name='want_how_many_cats',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='How many cats are wanted?'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='source',
            field=models.CharField(blank=True, choices=[('TNR', 'TNR'), ('Best Friends', 'Best Friends'), ('U', 'Unknown'), ('LAAS', 'LAAS'), ('Kindergarden', 'Kindergarden')], default='U', max_length=15, null=True),
        ),
    ]
