# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0006_auto_20180109_2011'),
        ('wc', '0005_auto_20180109_1904'),
    ]

    operations = [
    ]
