# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0007_merge_20180109_2035'),
        ('wc', '0006_auto_20180109_2152'),
    ]

    operations = [
    ]
